### ISSUE TITLE
Gravatar does not work

### ISSUE THREAD

**Issue by matthias-jauernig** [arielhr1987/leira-letter-avatar#6]
Plugin: Leira Letter Avatar
Plugin version: 1.3.7
Wordpress version: 6.3.2

We noticed that with the current version Gravatars are not shown for authors and commentators. So the "Use Gravatar profile picture if available" is active, but seems to have no effect. 
The functionality was still working some weeks ago, but we do not know what yields to the problem (Wordpress/plugin update or something else).

Is there anything we can do or debug here to see why Gravatars are not loaded?

**Comment by matthias-jauernig** [comment]
I found what's wrong: instead of using `http://%d.gravatar.com ...`, `https://...` should be used, then it works again.
The change has to be made in `public/class-leira-letter-avatar-public.php`

**Comment by fremmede** [comment]
I have the same error I don't see the avatar letter

**Comment by reatlat** [comment]
@matthias-jauernig your solution is legit! why its still not merged?

@arielhr1987 would you please take a loook and update the plugin? I use it across multiple websites and love it.

**Comment by reatlat** [comment]
@arielhr1987 Thank you so much 😍
